# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Tony's Website!
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/tyzhou06.github.io" # the subpath of the site
url: "https://tyzhou05.github.io/" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog?

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: tyzhou05@uw.edu
      link: mailto:tyzhou05@uw.edu
    #- name: WeChat
      #value: YourWeChatUsername
      #link: "#"
  follow:
    #- name: Instagram
      #link: http://instagram.com/tyzhouu
      #username: "@tyzhouu"
    #- name: TESTBOOK
     # link: http://facebook.com/tyzhou05
    - name: LinkedIn
      link: http://linkedin.com/in/tyzhou
    - name: GitHub
      link: http://github.com/tyzhou05
    #- name: Dribbble
    #  link: https://dribbble.com/YourDribbbleUsername
    #- name: RSS
     # link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
